### ISSUE TITLE
Implement output as Adobe Swatch

### ISSUE THREAD

**Issue by AdrianSimionov** [AdrianSimionov/color-sorting-cli#12]
The specifications of the ASE file are documented by reverse engineering in the below article:
https://carl.camera/default.aspx?section=color

Add an output option which will generate an Adobe Swatch ASE file instead of a text file.

An Objective-C implementation can be found below:
https://github.com/ramonpoca/ColorTools

**Comment by xlurio** [comment]
[Solved](13b77fcfb55635ecd90ce6c99abcae36e225dc43).
